### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xtuyaowu** [thunlp/THUTag#1]
1、控制台运行
usage:
 -algorithm <arg>    <no description>
 -config <arg>       <no description>
 -model_path <arg>   <no description>
 -realtime <arg>

2、直接写死参数报错 
Exception in thread "main" java.io.FileNotFoundException: \book.vcb (系统找不到指定的文件。)
请问 book.vcb  怎么生成，谢谢。

**Comment by YeDeming** [comment]
book.vcb由TrainWTM.java/TrainWAM.java/TrainWAMsample.java中语句
rn.exec(giza_path+File.separator + "mkcls -c80 -pbook -Vbook.vcb.classes opt",	null, modelDir)生成

请尝试在giza-pp文件中能使用make语句重新编译giza，也有可能是放的地方不对:

If you want to run WTM/WAM/WAM*, you need another three files GIZA++, mkcls, and plain2snt.out. Their default path is the same with the path of tagsuggest.jar.If you need change the path of them, you should add --giza_path="Path of them" as a parameter to the command.

另外，请确保使用linux环境

**Comment by brandyaptx** [comment]
我使用命令行 `java -Xmx5G -jar ./tagsuggest.jar evaluation.CrossValidator     --dataset=../traindata/bookPost70000.dat     --trainer_class=TrainWTM     --suggester_class=SMTTagSuggest     --num_folds=5     --config="dataType=DoubanPost;para=0.5;minwordfreq=10;mintagfreq=10;selfTrans=0.2;commonLimit=2"     --working_dir=./wtm_douban     --at_n=10     --report=./evaluation_WTMreal.txt` 同样报错`java.io.FileNotFoundException: ./wtm_douban/model.0.gz/book.vcb (No such file or directory)`

**Comment by YeDeming** [comment]
giza重新编译了吗?

**Comment by brandyaptx** [comment]
已经解决，之前因为没有训练，所以缺少book.vcb文件 @YeDeming

**Comment by zhangxinwq** [comment]
book.vcb文件怎么生成，谢谢
