### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by laurita** [thunlp/THUTag#5]
Hey,

I am trying to reproduce the baseline results you have in **Part III** in the [readme](https://github.com/thunlp/THUTag/blob/aeaa8253fbf543d170b8e2d64cc5c7d351cbf42f/readme.md). For example, I am running the command:
```
java -Xmx4G -jar /.../THUTag/demo/tagsuggest.jar evaluation.CrossValidator --dataset=/.../KeywordPost.dat.txt --trainer_class=TrainTFIDF --suggester_class=TFIDFTagSuggest --num_folds=5 --config="dataType=KeywordPost" --working_dir=/.../THUTag/ --at_n=10 --report=/.../evaluation_TFIDF.txt
```
but get different results. Also, what do you mean by "M_d=2,select the two keywords with the highest value". Could you specify what is the exact procedure of getting the results you have reported?

Thanks in advance!
Laura

**Comment by YeDeming** [comment]
Hi, Laura
M_d=2 means predict 2 keyword each document(the second line of evaluation_TFIDF.txt)
What is the result you got?

**Comment by laurita** [comment]
So M_d=2 means you report p@2, r@2 and F1@2?
With the command I sent above, the results I get look like this:

```
1 0.34649 0.01109 0.14729 0.00557 0.19949 0.00720 NaN NaN NaN NaN 4713
2 0.28808 0.00598 0.23600 0.00632 0.25104 0.00595 NaN NaN NaN NaN 7837
3 0.24602 0.00429 0.29840 0.00613 0.26183 0.00486 NaN NaN NaN NaN 10039
4 0.21399 0.00508 0.34317 0.00921 0.25679 0.00630 NaN NaN NaN NaN 11643
5 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
6 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
7 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
8 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
9 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
10 0.18743 0.00356 0.37396 0.00715 0.24389 0.00453 NaN NaN NaN NaN 12747
12747 68010 32387
```

So I assume, the `p@2 = 0.28808`, `r@2 = 0.23600` and `F1@2 = 0.25104`. In the table you have `0.25459`, `0.20083` and `0.21876` respectively. Do you have and idea why this is the case?

Thanks again,
Laura

**Comment by YeDeming** [comment]
```p@2 = 0.28808, r@2 = 0.23600 and F1@2 = 0.25104```  is the correct meaning.  Maybe I report wrong result for tf-idf.
